# Generated by Django 5.2.7 on 2025-10-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManagement_app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='expensemanagementapp_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='expensemanagementapp_user_permissions_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
